query GetItemsByName($id: String!, $options: Options) {
  itemsByName(id: $id, options: $options) {
    id
    name
    icon
    isActive
    createdAt {
      _
    }
    updatedAt {
      _
    }
  }
}
