query GetEstimate($id: ID!) {
  estimate(id: $id) {
    id
    name
    amount
    item {
      id
      name
    }
    month {
      name
      order
    }
    year
    isActive
    createdAt {
      _
    }
    updatedAt {
      _
    }
  }
}
