mutation UpdateEstimate($id: ID!, $input: EstimateUpdateInput!) {
  estimateUpdate(id: $id, input: $input) {
    id
    name
    amount
    item {
      id
      name
    }
    month {
      name
      order
    }
    year
    isActive
    createdAt {
      _
    }
    updatedAt {
      _
    }
  }
}
