query GetUser($id: ID!) {
  user(id: $id) {
    id
    phone
    name
    email
    total
    estimate
    expense
    isActive
    isLock
    createdAt {
      _
    }
    updatedAt {
      _
    }
  }
}
